import { ResourceNotFoundError } from "../errors";

export function notFoundErrorHandlerPlugin() {
  return new ResourceNotFoundError("Recurso n√£o encontrado.");
}
